version: '3.7'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'laravelapp'
    ports:
      - 80:80
    volumes:
      - ./:/var/www/
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/conf.d/:/usr/local/etc/php/
    environment:
      - APP_ENV=local
    networks:
      - laravel
  db:
    image: mysql:5.7
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ewalletdb
      MYSQL_USER: ewallet
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/db:/var/lib/mysql
    networks:
      - laravel

# Docker Networks
networks:
  laravel:
    driver: bridge