version: '3.7'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'laravelapp'
    ports:
      - 80:80
    volumes:
      - .:/var/www/
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/conf.d/:/usr/local/etc/php/
    environment:
      - APP_ENV=local
    networks:
      backend:
        aliases:
          - app
  db:
    image: mysql:5.7
    container_name: mysql
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ewalletdb
      - MYSQL_USER=ewallet
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./docker/db:/var/lib/mysql
    networks:
      backend:
        aliases:
          - db

# Docker Networks
networks:
  backend:
    name: backend-network